# Generated by Django 6.0.4 on 2026-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_puzzleoutput_puzzledependency_outputacquired'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='category',
            field=models.CharField(choices=[('logical', 'Logical'), ('physical', 'Physical'), ('code', 'Code-breaking'), ('search', 'Search & discovery')], default='logical', max_length=20),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='is_parallel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='subtype',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
