# Generated by Django 6.0.4 on 2026-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='paused_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
