# Generated by Django 6.0.4 on 2026-04-16 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamesession_paused_at_gamesession_paused_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleattempt',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
