# Generated by Django 6.0.4 on 2026-04-16 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_puzzleattempt_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('code', 'Numeric/text code'), ('key', 'Physical key'), ('item', 'Item or object'), ('info', 'Information / clue')], max_length=20)),
                ('output_value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='games.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_required', models.BooleanField(default=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='games.puzzle')),
                ('requires_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='games.puzzleoutput')),
            ],
            options={
                'unique_together': {('puzzle', 'requires_output')},
            },
        ),
        migrations.CreateModel(
            name='OutputAcquired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired_outputs', to='games.gamesession')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.puzzleoutput')),
            ],
            options={
                'unique_together': {('session', 'output')},
            },
        ),
    ]
